create database IncidentOntology;
show databases;
use IncidentOntology;
create table ServiceHasIncdient (Subject varchar(20), Predicate varchar (20), Object varchar(20), ID varchar(10) primary key );
create table HasIncident (Service varchar (50), Incident varchar (50), ID smallint auto_increment primary key); 
create table Incident (IncidentTicketNumber varchar(10) primary key, IncidentType ENUM ('Cloud','Virtualization', 'Network', 'System', 'Collabration', 'Computer', 'Printer', 'Scanner', 'IP Phone', 'Utility'), IncidentDetectionDate datetime, IncidentDuration varchar (20), IncidentAgeDay int, IncidentAgeHour int, IncidentAgeMinute int, IncidentHierarchyTier1 ENUM('Request', 'Report', 'Feedback'), IncidentHierarchyTier2 ENUM('Hardware', 'Software', 'Change', 'Procedure', 'Incident'), IncidentHierarchyTier3 varchar (50), IncidentIdentificationDate date, IncidentReportedHour time, IncidentStatus varchar (20), IncidentSummary varchar(50));
create table Service (ServiceCategory ENUM ('Print Service', 'Email Service', 'Cloud Service', 'Internet Service'), ServiceStartDate datetime, ServiceStopDate datetime);
show tables;

create table OrganizationHasLocation (Subject varchar (20), Predicate varchar (20), Object varchar (20), ID varchar (10) primary key);
create table Organization (OrganizationName varchar (30));
create table SubjectPredicateObject (Subject varchar(20), Predicate varchar (20), Object varchar(20), ID varchar(10) primary key );
insert into SubjectPredicateObject values ("Service","has","Incident","001");
insert into SubjectPredicateObject values ("Service","has","Problem","001");
insert into SubjectPredicateObject values ("Organization","has","Location","001");
select * from SubjectPredicatObject;
create table SubjectPredicatObject (Subject varchar(20), 
ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
Predicate varchar (20), Object varchar(20), 
PRIMARY KEY (ID));
insert into SubjectPredicatObject values (NULL, "Service","has","Incident");


show tables;

Select * from SubjectPredicateObjectTable;

create table SubjectPredicateObjectTable (Subject varchar(20), Predicate varchar (20), Object varchar(20), ID varchar(10) primary key );
insert into SubjectPredicateObjectTable values ("Organization","hasLocation","Location","001");
insert into SubjectPredicateObjectTable values ("Service","hasProblem","Problem","002");
insert into SubjectPredicateObjectTable values ("Service","hasIncident","Incident","003");
insert into SubjectPredicateObjectTable values ("Incident","assignedTo","IT","004");
insert into SubjectPredicateObjectTable values ("Person","hasAccess","Access","005");
insert into SubjectPredicateObjectTable values ("Factor","hasAnEffectOn","Service_Provider_Side","006");
insert into SubjectPredicateObjectTable values ("Change","hasAnInterruptionOn","Service","007");
insert into SubjectPredicateObjectTable values ("Service_Provider_Side","hasAParticipant","Person","008");
insert into SubjectPredicateObjectTable values ("Incident","hasCategory","Asset","009");
insert into SubjectPredicateObjectTable values ("Incident","hasCause","Root_Cause","010");
insert into SubjectPredicateObjectTable values ("Incident","hasClosure","Closure","011");
insert into SubjectPredicateObjectTable values ("Incident","hasCommunication","Communication","012");
insert into SubjectPredicateObjectTable values ("Problem","hasAssociated","Incident","013");
insert into SubjectPredicateObjectTable values ("Device","hasCorporateOWner","Corporation","014");
insert into SubjectPredicateObjectTable values ("Pain_Value_Analysis","hasCost","Cost","015");
insert into SubjectPredicateObjectTable values ("System","hasDeployment","Unit","016");
insert into SubjectPredicateObjectTable values ("Incident","hasDiagnosis","Diagnosis","017");
insert into SubjectPredicateObjectTable values ("Pain_Value_Analysis","hasDuration","Duration","018");
insert into SubjectPredicateObjectTable values ("Incident","hasEscalation","Escalation","019");
insert into SubjectPredicateObjectTable values ("Process","hasFactor","Factor","020");
insert into SubjectPredicateObjectTable values ("Device","hasHardware","Hardware","021");
insert into SubjectPredicateObjectTable values ("Incident","hasHistory","History","022");
insert into SubjectPredicateObjectTable values ("Incident","hasIdentifiedCategory","Category","023");
insert into SubjectPredicateObjectTable values ("Incident","hasImpact","Impact","024");
insert into SubjectPredicateObjectTable values ("Pain_Value_Analysis","hasImpactedUSerType","Impacted_User","025");
insert into SubjectPredicateObjectTable values ("Unit","hasIT","IT","026");
insert into SubjectPredicateObjectTable values ("Unit","hasNonIT","NonIT","027");
insert into SubjectPredicateObjectTable values ("Device","hasOwnership","Ownership","028");
insert into SubjectPredicateObjectTable values ("Impact","hasPainValueAnalysis","Pain_Value_Analysis","029");
insert into SubjectPredicateObjectTable values ("Device","hasIndividualOwner","Individual","030");
insert into SubjectPredicateObjectTable values ("Incident","hasPrioritization","Prioritization","031");
insert into SubjectPredicateObjectTable values ("Incident","hasPriority","Priority","032");
insert into SubjectPredicateObjectTable values ("Prioritization","hasPriorityLevel","Priority","033");
insert into SubjectPredicateObjectTable values ("Incident","hasRemediation","Remediation","034");
insert into SubjectPredicateObjectTable values ("Incident","hasReporter","Person","035");
insert into SubjectPredicateObjectTable values ("Organization","hasService","Service","036");
insert into SubjectPredicateObjectTable values ("Device","hasSoftware","Software","037");
insert into SubjectPredicateObjectTable values ("System","hasSource","Source","038");
insert into SubjectPredicateObjectTable values ("Impact","hasThreat","Threat","039");
insert into SubjectPredicateObjectTable values ("Device","hasType","Type","040");
insert into SubjectPredicateObjectTable values ("Person","hasUnit","Unit","041");
insert into SubjectPredicateObjectTable values ("Service","interruptedBy","Change","042");
insert into SubjectPredicateObjectTable values ("Person","involvedIn","Root_Cause","043");
insert into SubjectPredicateObjectTable values ("Asset","involvedIn","Root_Cause","044");
insert into SubjectPredicateObjectTable values ("Process","involvedIn","Root_Cause","045");
insert into SubjectPredicateObjectTable values ("Workload","isA","Factor","046");
insert into SubjectPredicateObjectTable values ("Timescale","isA","Factor","047");
insert into SubjectPredicateObjectTable values ("Priority","isA","Factor","048");
insert into SubjectPredicateObjectTable values ("Threshold","isA","Factor","049");
insert into SubjectPredicateObjectTable values ("Performance","isA","Factor","050");
insert into SubjectPredicateObjectTable values ("Printer","isAKindOf","Device","051");
insert into SubjectPredicateObjectTable values ("Scanner","isAKindOf","Device","052");
insert into SubjectPredicateObjectTable values ("IP_Phone","isAKindOf","Device","053");
insert into SubjectPredicateObjectTable values ("Computer","isAKindOf","Device","054");
insert into SubjectPredicateObjectTable values ("Utility","isAKindOf","Device","055");
insert into SubjectPredicateObjectTable values ("Broadband","isASourceOf","Network","056");
insert into SubjectPredicateObjectTable values ("VSAT","isASourceOf","Network","057");
insert into SubjectPredicateObjectTable values ("Cellular","isASourceOf","Network","058");
insert into SubjectPredicateObjectTable values ("ISP","isASourceOf","Network","059");
insert into SubjectPredicateObjectTable values ("Login","isExpectedFrom","Client_Side","060");
insert into SubjectPredicateObjectTable values ("Signup","isExpectedFrom","Client_Side","061");
insert into SubjectPredicateObjectTable values ("Report","isExpectedFrom","Client_Side","062");
insert into SubjectPredicateObjectTable values ("Request","isExpectedFrom","Client_Side","063");
insert into SubjectPredicateObjectTable values ("Unit","participateIn","Change","064");
insert into SubjectPredicateObjectTable values ("Collabration","isPartOf","Infrastructure","065");
insert into SubjectPredicateObjectTable values ("Virtualization","isPartOf","Infrastructure","066");
insert into SubjectPredicateObjectTable values ("Network","isPartOf","Infrastructure","067");
insert into SubjectPredicateObjectTable values ("Cloud","isPartOf","Infrastructure","068");
insert into SubjectPredicateObjectTable values ("Device","isPartOf","Infrastructure","069");
insert into SubjectPredicateObjectTable values ("System","isPartOf","Infrastructure","070");
insert into SubjectPredicateObjectTable values ("IM","isUsedFor","Collabration","071");
insert into SubjectPredicateObjectTable values ("VC","isUsedFor","Collabration","072");

create table Location (Location_ID varchar (10) primary key , Country varchar (40), Continent varchar (40), Region varchar (40), City varchar (40), Building varchar (40), Room_Number varchar (40));
create table Unit (Unit_Code varchar (10), Unit_Name varchar (30), Unit_Manager varchar (30), Unit_Members varchar (150), Number_Of_Employees int);
create table IT (IT_Sub_Unit_Name varchar (30), Contact_Person varchar(30), Email varchar(20) primary key);
create table Non_IT (Contact_Person varchar (20));
create table problem (Problem_Code INT AUTO_INCREMENT PRIMARY KEY, Problem_Start_Date date, Problem_End_Date date, Problem_Summary varchar (50), Problem_Category enum ('Power Issue', 'Internet Problem'));
create table Impact (Impact_Code INT auto_increment PRIMARY KEY, Impact_Summary varchar (100), Severe_Status enum ('High', 'Medium', 'Low'));
create table Pain_Value_Analysis (Number_of_Related_Incidents int, Last_Reported_Date datetime, Pain_Value double, Weighting_Factor varchar (20));
create table History (Incident_Reported_Date date, Incident_Reported_Hour time, Ticket_Age datetime, Aging_Status enum ('Normal', 'Aging', 'Aged'));
create table Communication (Sender varchar (30), Intended_Receiver varchar (30), message varchar (200));
create table Cost (Direct_Product_Cost double, Direct_Labour_Cost double, Direct_Expense_Cost double);
create table Threshold (Minimum_Number_Of_Related_Incidents int, Maximum_Number_Of_Related_Incidents int);
create table Resolution (Property_Number varchar (10), Asset_Category enum ('IP Phone', 'Computer', 'Printer', 'Scanner', 'Utility'), Asset_Name varchar (20), Subpart varchar (20), Root_Cause_Summary varchar (100), Operational_Category_Tier1 enum ('Cloud','Virtualization', 'Network', 'System', 'Collabration', 'Device'), Operational_Category_Tier2 enum ('Printer','Scanner', 'IP Phone', 'Utility', 'Computer', 'Microsoft Office 365'),  Operational_Category_Tier3 enum ('HP Laserjet 9050 Printer','Scanejet 2100', 'Cisco IP Phone', 'Outlook 2016', 'Lenovo T460s Laptop'), Resolution varchar (100), Resolution_Date date, Resolution_Time time);
create table Escalation (Escalated_From_Unit varchar (50), Escalated_To_Unit varchar (50), Escalated_From_Technician varchar (30), Escalation_Date date, Escalation_Time time, Attempted_Resolution_Summary varchar (100));
create table Closure (Closure_Date date, Closure_Time time, Workaround_Type enum ('Existed', 'New'), Workaround_Note varchar(1000));
create table Remediation (Temporary_Fix_Note varchar(100), Remediation_Date date, Remediation_Time time);
create table Workload (Number_Of_Assigned_Tickets int, Number_Of_Working_Tickets int, Number_Of_Closed_Tickets int, Number_Of_Opened_Tickets int, Number_Of_Escalated_Tickets int);
create table Performance (Resolution_Time datetime, Remediation_Time datetime, Escalation_Time datetime, Incident_Age datetime);
create table Client_Side (Fullname varchar (50), Department varchar (30), Country varchar (20), City varchar (15), Region varchar (20), Branch varchar (20), Room_Number varchar (5), Client_ID varchar (10) primary key);
create table Request (Request_Date date, Request_Time time, Request_Type varchar (30), Request_Category enum ('1st Time', '2nd Time', '3rd Time'), Request_Content varchar (500), Request_Summary varchar (100), Request_Hierarchy_Tier1 enum ('Hardware', 'Software', 'Procedure'), Request_Hierarchy_Tier2 enum ('Change', 'Replace', 'Borrow'),Request_Hierarchy_Tier3 enum('Install','Mouse', 'Laptop Charger'));
create table Signup (Signup_Date date, Signup_Time time, Signup_Service_Name varchar (30), Signup_Service_Status varchar(30));
create table Login (Username varchar (30), Client_Password varchar (30), Account_Type enum ('AD', 'Desktop', 'Email', 'Server', 'Internet','System'), User_Category enum ('Internal', 'External'));
select * from Login;
ALTER TABLE SubjectPredicateObjectTable MODIFY Subject varchar(40);
ALTER TABLE SubjectPredicateObjectTable MODIFY Predicate varchar(40);
ALTER TABLE SubjectPredicateObjectTable MODIFY Object varchar(40);